### ISSUE TITLE
The dev tool does not work 

### ISSUE THREAD

**Issue by Asscobara** [reduxjs/redux-devtools#1198]
The error I get from the dev tools on the extension window:

window.bundle.js:2 TypeError: Cannot read properties of undefined (reading 'action')
    at o.value (window.bundle.js:2:1651470)
    at o.value (window.bundle.js:2:1650604)
    at ds (window.bundle.js:2:153189)
    at Pu (window.bundle.js:2:169890)
    at t.unstable_runWithPriority (window.bundle.js:2:1032894)
    at $o (window.bundle.js:2:112201)
    at Cu (window.bundle.js:2:166629)
    at mu (window.bundle.js:2:162828)
    at window.bundle.js:2:112424
    at t.unstable_runWithPriority (window.bundle.js:2:1032894)
as @ window.bundle.js:2
window.bundle.js:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'action')
    at o.value (window.bundle.js:2:1651470)
    at o.value (window.bundle.js:2:1650604)
    at ds (window.bundle.js:2:153189)
    at Pu (window.bundle.js:2:169890)
    at t.unstable_runWithPriority (window.bundle.js:2:1032894)
    at $o (window.bundle.js:2:112201)
    at Cu (window.bundle.js:2:166629)
    at mu (window.bundle.js:2:162828)
    at window.bundle.js:2:112424
    at t.unstable_runWithPriority (window.bundle.js:2:1032894)
    
    Any idea what's wrong?

**Comment by HouCoder** [comment]
I had to reinstall the extension to make it work.

**Comment by komali2** [comment]
I'm having this error now. It will take time for me to produce a working, shareable example, as our app is massive (and, sadly, proprietary). In doing so, perhaps I will simply discover the issue? So I will post what I can here for now, and hope to expedite the finding of that solution. 

```
        "react": "^17.0.2",
        "redux": "^4.1.2",

```

Redux devtools version: Version
3.0.11

Chrome version Version 103.0.5060.114 (Official Build) (64-bit)

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

When I open redux devtools, I see a blank page. If I inspect the frame, I get uncaught errors in the console for redux devtools: 

```
Uncaught Error: No location name for view with id chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljdRedux
    at Ii.locationNameForViewId (legacy.js:1:118242)
    at Vi.onContextMenu (legacy.js:1:138953)
    at ri.tabContextMenu (legacy.js:1:113430)

TypeError: Cannot read properties of undefined (reading 'action')
    at o.value (window.bundle.js:2:1651470)
    at o.value (window.bundle.js:2:1650604)
    at ds (window.bundle.js:2:153189)
    at Pu (window.bundle.js:2:169890)
    at t.unstable_runWithPriority (window.bundle.js:2:1032894)
    at $o (window.bundle.js:2:112201)
    at Cu (window.bundle.js:2:166629)
    at mu (window.bundle.js:2:162828)
    at window.bundle.js:2:112424
    at t.unstable_runWithPriority (window.bundle.js:2:1032894)
as @ window.bundle.js:2
window.bundle.js:2 

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'action')
    at o.value (window.bundle.js:2:1651470)
    at o.value (window.bundle.js:2:1650604)
    at ds (window.bundle.js:2:153189)
    at Pu (window.bundle.js:2:169890)
    at t.unstable_runWithPriority (window.bundle.js:2:1032894)
    at $o (window.bundle.js:2:112201)
    at Cu (window.bundle.js:2:166629)
    at mu (window.bundle.js:2:162828)
    at window.bundle.js:2:112424
    at t.unstable_runWithPriority (window.bundle.js:2:1032894)
```

It looks like this: 

Our app chrome frame: 

![Screenshot from 2022-08-17 11-01-05](https://user-images.githubusercontent.com/8533113/185025405-1d1e7bed-4ff8-4d47-98ea-ca5fccf3239b.png)


Redux devtools chrome frame:

![Screenshot from 2022-08-17 11-01-12](https://user-images.githubusercontent.com/8533113/185025424-8fb2a7ef-fa7f-45d5-9104-6ad474d9a1fb.png)


I have tried:

1. Restarting my computer
2. Restarting chrome
3. Uninstalling redux devtools, then doing step 1 and 2 in variations between reinstalls

The issue persists. 

My store is built as such:

```
import { configureStore } from '@reduxjs/toolkit';
import {
  useDispatch as useAppDispatch,
  useSelector as useAppSelector,
  TypedUseSelectorHook,
} from 'react-redux';

import { persistStore } from 'redux-persist';

import rootReducer from './reducer';


const store = configureStore({
  reducer: rootReducer,
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware({
      serializableCheck: false,
      immutableCheck: false,
    }),
  devTools: true,
});

const persister = persistStore(store);

export type RootState = ReturnType<typeof rootReducer>;

export type AppDispatch = typeof store.dispatch;

const { dispatch } = store;

const useDispatch = () => useAppDispatch<AppDispatch>();
const useSelector: TypedUseSelectorHook<RootState> = useAppSelector;

export { store, persister, dispatch, useSelector, useDispatch };
```

**Comment by chipallen2** [comment]
Any advice on how to get around this error. I tried reinstalling the extension in chrome but the error still persists?

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'action')
    at o.value (window.bundle.js:formatted:89391:51)
    at o.value (window.bundle.js:formatted:89342:26)
    at ds (window.bundle.js:formatted:8421:52)
    at Pu (window.bundle.js:formatted:9541:47)
    at t.unstable_runWithPriority (window.bundle.js:formatted:57353:28)
    at $o (window.bundle.js:formatted:5954:17)
    at Cu (window.bundle.js:formatted:9330:24)
    at mu (window.bundle.js:formatted:9056:17)
    at window.bundle.js:formatted:5978:41
    at t.unstable_runWithPriority (window.bundle.js:formatted:57353:28)
```

Which seems to be this line of code in the 

```
this.setState({
      stackFrames: [],
      showDocsLink: !!o.action && !!o.action.type && "@@INIT" !== o.action.type
  })
  ```

**Comment by komali2** [comment]
I have reinstalled redux dev tools one final time, and now it works? `3.0.11` is still the same version lol, maybe a chrome update fixed it?

**Comment by Bartel-C8** [comment]
In my case I got this stack trace:

```
  [36886:1012/133754.961339:ERROR:CONSOLE(0)] "Error in event handler: TypeError: Cannot read properties of undefined (reading 'action')
      at o.value (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/window.bundle.js:2:1746278)
      at Ha (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/window.bundle.js:2:139049)
      at Va (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/window.bundle.js:2:138848)
      at Hs (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/window.bundle.js:2:179461)
      at Eu (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/window.bundle.js:2:165737)
      at Ou (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/window.bundle.js:2:165665)
      at Su (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/window.bundle.js:2:165528)
      at mu (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/window.bundle.js:2:162603)
      at chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/window.bundle.js:2:112424
      at t.unstable_runWithPriority (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/window.bundle.js:2:1032894)", source: chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/window.html (0)
```

Which maps to this line: https://github.com/reduxjs/redux-devtools/blob/main/packages/redux-devtools-slider-monitor/src/SliderMonitor.tsx#L333

**Comment by Bartel-C8** [comment]
This is really annoying. Can't really get around it. Is there a possible fix?

Maybe it's fixed already, but there hasn't been a new version pushed to the Chrome Web Store since 3.0.11

**Comment by Methuselah96** [comment]
Is it possible that you're dispatching an `undefined` action?

**Comment by Bartel-C8** [comment]
Could be, but not intentional at least. How could I find this out?
(Typescript project, so I suspect typescript should complain anyway when dispatching an undefined action?)

But, I do have multiple filters/sanitizers in place for Redux (in order to get better Redux Devtools performance):
I am using: `actionsDenylist`, `actionSanitizer, `stateSanitizer` and  `predicate`.

Strange thing is that I have this system in place for quite some time, and only recently noticing these "crashes".

**Comment by Bartel-C8** [comment]
But shouldn't this line https://github.com/reduxjs/redux-devtools/blob/main/packages/redux-devtools-slider-monitor/src/SliderMonitor.tsx#L333 just not get an extra check that if `actionsById[actionId]` is undefined that `actionType = '<UNDEFINED>'` ?

**Comment by Methuselah96** [comment]
Maybe, or maybe it indicates there's a bug somewhere else. I believe the intention is that the action should never be `undefined`.

**Comment by Methuselah96** [comment]
Can you try [deleting the IndexedDB for the devtools](https://github.com/reduxjs/redux-devtools/issues/1081#issuecomment-1051016533) and see if that changes anything?

Can you give me more details about when it crashes? Does it happen as soon as you open the devtools, or does it work initially and then crash?

**Comment by Bartel-C8** [comment]
Commenting out `actionsDenylist` (was named `actionsBlacklist` before) did the trick for me.
I already was using `predicate` as well to filter out actions, so maybe it was a bug there?

But what I think could be happening(?):
I have set a latency of 2000ms. And I am dispatching fairly many actions. One of them was being blacklisted in `actionsDenylist`. Could it be that the dispatching of some other (frequent) action, renders that the (blacklisted) gives that `undefined` action, somewhere in a old list?

**Comment by SlamTheDragon** [comment]
I may be experiencing the same issue, the only difference is that the devtools occasionally "fix itself"(?)
Other than that the issue gets progressively worse up to the point that the panel won't show itself.

I have the v3.0.19 installed, I've tried some solutions listed here but it seems to not work

```
Stack Trace

window.bundle.js:2 (ds)
window.bundle.js:2 (r.callback)
window.bundle.js:2 (zi)
window.bundle.js:2 (xl)
window.bundle.js:2 (wl)
window.bundle.js:2 (bl)
window.bundle.js:2 (anonymous function)
window.bundle.js:2 (Su)
window.bundle.js:2 (uu)
window.bundle.js:2 (Uo)
window.bundle.js:2 (anonymous function)
window.bundle.js:2 (Su)
window.bundle.js:2 (iu)
window.bundle.js:2 (S)
window.bundle.js:2 (T)

Source:
           /*! For license information please see window.bundle.js.LICENSE.txt */
--->       (()=>{var e,t,r={30642:function(e,t,r){var n,o,i=this&&this.__generator||function(e,t){va...
           display: flex;
           height: 100%;
           width: 100%;
           flex-flow: column nowrap;
           overflow: auto;
           ${""}
           backgroun...
```
