### ISSUE TITLE
Cannot read property 'liftedStore' of undefined in instrument package - coherent

### ISSUE THREAD

**Issue by Stranget0** [reduxjs/redux-devtools#1347]
I'm working on a UI which is used in an unreal engine game implemented via Coherent, which is a custom JS/HTML/CSS environment for this game engine.
When trying to implement remote redux devtools with redux-devtools/cli and redux-devtools/remote I'm getting a
`Cannot read property 'liftedStore' of undefined` in `liftReducerWith`, which is probably because of how coherent works, or because of how project is set up.

For Redux, I'm using:
```
"socketcluster-client": "^17.1.1"
"redux": "^4.1.2",
"redux-orm": "^0.16.2",
"redux-thunk": "^2.4.1",
"@redux-devtools/remote": "^0.8.0",
```
And @redux-devtools/cli as global package

**Comment by markerikson** [comment]
Can you post the actual stack trace, and as much as actual related setup as possible? Can't really give any feedback without knowing what you're actually doing in the codebase.

**Comment by Stranget0** [comment]
@markerikson 

stack trace:
```
Uncaught  TypeError: Cannot read property 'liftedStore' of undefined
    at eval (.../node_modules/@redux-devtools/remote/lib/esm/devTools.js:147:68)
    at liftReducerWith (.../node_modules/@redux-devtools/instrument/lib/esm/instrument.js:302:19)
    at liftReducer (.../node_modules/@redux-devtools/instrument/lib/esm/instrument.js:814:16)
    at eval (.../node_modules/@redux-devtools/instrument/lib/esm/instrument.js:817:37)
    at eval (.../node_modules/@redux-devtools/remote/lib/esm/devTools.js:172:13)
    at eval (.../node_modules/redux/es/redux.js:693:31)
    at eval (.../node_modules/@redux-devtools/remote/lib/esm/devTools.js:300:34)
    at createStore (.../node_modules/redux/es/redux.js:165:33)
    at eval (.../ww3hub/src/plugins/store.ts:47:37)
    at Object../src/plugins/store.ts (coui://uiresources/main.js:16166:1)
 ```

store.ts file
```ts
...
import {
	createStore,
	applyMiddleware,
	combineReducers,
	Store,
	AnyAction,
} from "redux";
import thunk, { ThunkDispatch } from "redux-thunk";
import { composeWithDevTools } from "@redux-devtools/remote";

...

const composeEnhancers  = composeWithDevTools({
	port: 8000,
	sendOnError:2,
	shouldStartLocked: true,
	suppressConnectErrors: false
});

const store: Store<RootState> = createStore(
	rootReducer,
	undefined,
	composeEnhancers(applyMiddleware<unknown, RootState>(thunk) as any ) as StoreEnhancer<{}, RootState>
);
export default store;
```

**Comment by markerikson** [comment]
Hmm.  Odd.  Looking at those files in Unpkg, the line numbers don't seem to match.  I don't see a mention of `liftedStore` on line 147 in https://unpkg.com/browse/@redux-devtools/remote@0.8.0/lib/esm/devTools.js , and `liftReducerWith` isn't on line 302 in https://unpkg.com/browse/@redux-devtools/instrument@2.1.0/lib/esm/instrument.js .

Unfortunately I don't have any real suggestions here.

**Comment by Stranget0** [comment]
@markerikson The code runs through babel, so I think this can change. 
The problematic code it points me to looks like this (after parsed):
```js
  
    (0,_babel_runtime_helpers_defineProperty__WEBPACK_IMPORTED_MODULE_0__["default"])(this, "monitorReducer", function () {
      let state = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};
      let action = arguments.length > 1 ? arguments[1] : undefined;
      _this.lastAction = action.type;
      if (!_this.started && _this.sendOnError === 2 && _this.store.liftedStore) async(_this.checkForReducerErrors);else if (action.action) {
        if (_this.startOn && !_this.started && _this.startOn.indexOf(action.action.type) !== -1) async(_this.start);else if (_this.stopOn && _this.started && _this.stopOn.indexOf(action.action.type) !== -1) async(_this.stop);else if (_this.sendOn && !_this.started && _this.sendOn.indexOf(action.action.type) !== -1) async(_this.send);
      }
      return state;
    });
      ```
      
      When removing  `sendOnError: 2` from settings it got fixed, but sadly I got struct by crypto error:
      
       Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported
    at rng (D:/Warsztat_WIP/ww3hub/node_modules/uuid/dist/esm-browser/rng.js:18:13)
    at Module.v4 (D:/Warsztat_WIP/ww3hub/node_modules/uuid/dist/esm-browser/v4.js:9:96)
    at Object.create (D:/Warsztat_WIP/ww3hub/node_modules/socketcluster-client/lib/factory.js:44:20)
    at Object.module.exports.create (D:/Warsztat_WIP/ww3hub/node_modules/socketcluster-client/index.js:9:18)
    at DevToolsEnhancer.eval [as start] (D:/Warsztat_WIP/ww3hub/node_modules/@redux-devtools/remote/lib/esm/devTools.js:103:71)
    at eval (D:/Warsztat_WIP/ww3hub/node_modules/@redux-devtools/remote/lib/esm/devTools.js:173:31)
    at eval (D:/Warsztat_WIP/ww3hub/node_modules/redux/es/redux.js:693:31)
    at eval (D:/Warsztat_WIP/ww3hub/node_modules/@redux-devtools/remote/lib/esm/devTools.js:300:34)
    at createStore (D:/Warsztat_WIP/ww3hub/node_modules/redux/es/redux.js:165:33)
    at eval (D:/Warsztat_WIP/ww3hub/src/plugins/store.ts:71:37)
    
    It says to transpile it with babel in my case, but I guess I need to add a polyfill exclusively, as babel doesn't seem to handle it currently

**Comment by markerikson** [comment]
Yeah, Babel definitely isn't going to do anything with polyfilling platform APIs.

**Comment by Stranget0** [comment]
@markerikson 
Alright, after polyfilling that and also url and url-search-parameters my project runs.
Although, now I'm getting `SocketProtocolError: Socket hung up` error

**Comment by Stranget0** [comment]
@markerikson 
Not sure if this is the case, but the logs when starting redux-dev-server stop at `Migrations are finished`
![image](https://user-images.githubusercontent.com/22750053/217329156-4de5355a-b2fa-417a-a713-0714ca0ccc2e.png)
Can this be related?

**Comment by markerikson** [comment]
Unfortunately I don't know anything else about the actual RDT internals here, and especially about the "remote" functionality.

**Comment by Stranget0** [comment]
@markerikson 
As an alternative - is there an option to implement `stateSanitiser` together with manual integration as a react component?
https://github.com/reduxjs/redux-devtools/blob/main/docs/Walkthrough.md#manual-integration

I'm not able to use an extension, so I don't have `window.__REDUX_DEVTOOLS_EXTENSION__`

**Comment by markerikson** [comment]
@Stranget0 I'm not sure what you're asking there.

Could you try to post as much of your relevant code as possible so I can try to understand what you're doing?

**Comment by Stranget0** [comment]
@markerikson 
I have another approach for this to implement monitor as a component, so I don't require the server.
I also need to hide `entities` from State, as it is a big object with data - so I also need stateSanitizer

In this version I have store configured in such way:

store.ts
```tsx
const enhancer = compose(...(isDev ? devEnhancers : prodEnhancers)) as any;

const store: Store<RootState> = createStore(rootReducer, undefined, enhancer);
```
enhancers.prod.ts
```ts
import { applyMiddleware } from "redux"
import thunk from "redux-thunk"

const prodEnhancers = [applyMiddleware(thunk)]
export default prodEnhancers
```

enhancers.dev.ts
```ts
import DevTools from "./DevTools/DevTools";
import prodEnhancers from "./enhancers.prod";

const devEnhancers = [
	...prodEnhancers,
	DevTools.instrument(),
];
export default devEnhancers;
```

DevTools.tsx
```tsx
import React from "react";

import { createDevTools } from "@redux-devtools/core";

import { LogMonitor } from "@redux-devtools/log-monitor";
import classes from './DevTools.module.scss'

const DevTools = createDevTools(<div className={classes.DevTools}>
	<LogMonitor theme="tomorrow" />
</div>);

export default DevTools;
```

DevToolsRoot.tsx (used in App.tsx)
```ts
import { isDev } from "@/utils";
import DevTools from "./DevTools";

export default isDev ? DevTools : ()=> null;
```
(Will hide properly for prod once I figure out this works)

Now I need to somehow add the sanitizers, although It seems that DevTool.instrument() is not a place for such setting (or is it?)

**Comment by markerikson** [comment]
What is your `DevTools.instrument()` enhancer, exactly?  Where is that coming from originally (like, is it being imported from one of the Redux DevTools packages)?

FWIW, looking at the source, I'm pretty sure you can pass `stateSanitizer` directly to `composeWithDevTools`, right next to the `shouldStartLocked` and `suppressConnectErrors` options you're already passing in.

**Comment by Stranget0** [comment]
It is from a class component made by `createDevTools` from `@redux-devtools/core`.
In this version I am sadly not able to use `composeWithDevTools`, as this is a separate implementation.
This one is made by following [how to set up redux devtools as a component](https://github.com/reduxjs/redux-devtools/blob/main/docs/Walkthrough.md#manual-integration).

**Comment by markerikson** [comment]
Is there a reason _why_ you can't use `composeWithDevTools`?  Or at least copy-paste the implementation?

The sanitization logic is built into that already.

**Comment by Stranget0** [comment]
From what I understand - this implementation is used for remote devtool monitor and sending the data here.
In this example I don't have a remote monitor. Only a monitor component which is connected by DevTool.instrument().

So, I guess composing this won't change the data passed to the DevTool?

**Comment by markerikson** [comment]
I'll be honest, it's really hard to answer your questions without seeing the _actual_ code that you've put together.  I realize that you've probably got a much larger application, but it would be _reallllly_ helpful if you could extract the Redux store-related code, including _all_ the DevTools pieces that you're using, and put those up in a CodeSandbox or repo that I can look at. Doesn't have to run or even compile, but I can't really offer suggestions without being able to understand how you're trying to piece things together right now.

**Comment by Stranget0** [comment]
Alright, I'll do that tomorrow and send the example

Anyway, thank you for your time <3

**Comment by Stranget0** [comment]
@markerikson 
I have set up a sandbox with second approach, although I am getting an error there
[link](https://codesandbox.io/s/modern-cdn-hrdps9?file=/src/App.js)

**Comment by markerikson** [comment]
@Stranget0 : thank you, that made it _much_ easier for me to investigate.

So there's two bugs in your example:

First, the `createDevTools` function specifically wants one React element, and it _must_ contain the actual monitor component, _without_ any wrapping elements.  I see you added a `<div>` wrapper around `<LogMonitor>`, but that won't work - it must _only_ be `<LogMonitor>`.

The second issue is an imports mismatch.  Apparently, `@redux-devtools/log-monitor` _used_ to do `export default LogMonitor`, but now it does `export { LogMonitor }` as a _named_ export.  So, you need to change that file to:

```ts
import React from "react";

// Exported from redux-devtools
import { createDevTools } from "@redux-devtools/core";

// Monitors are separate packages, and you can make a custom one
import { LogMonitor } from "@redux-devtools/log-monitor";
import { DockMonitor } from "@redux-devtools/dock-monitor";

// breaks without div wrapper
const component = <LogMonitor theme="tomorrow" />;

const DevTools = createDevTools(component);

export default DevTools;
```

Now, for some reason when I do that the sandbox example breaks with a _really_ weird error inside of React ( `Uncaught TypeError: Cannot create property '_updatedFibers' on number '0'` ), but that shouldn't have anything to do with the devtools stuff at this point.

Try making those changes in your reall app and see what happens.

Also, while this isn't specifically related to the issue: I would _strongly_ encourage you to use Redux Toolkit to set up the Redux store and write your logic, rather than "hand-writing" the code yourself:

- https://redux.js.org/introduction/why-rtk-is-redux-today
- https://redux.js.org/tutorials/essentials/part-2-app-structure#creating-the-redux-store
- https://redux.js.org/tutorials/fundamentals/part-8-modern-redux
- https://blog.isquaredsoftware.com/2022/06/presentations-modern-redux-rtk/

You might need to set `devTools: false` in `configureStore()`, and then pass in your own devtools enhancer as part of the `enhancers` option.  Still shorter than trying to write it all by hand.

**Comment by Stranget0** [comment]
@markerikson Sorry, I have some other things to do now, will return to this issue once I'm finished
