### ISSUE TITLE
_socketclusterClient2.default.connect is not a function

### ISSUE THREAD

**Issue by GeneZharov** [reduxjs/redux-devtools#1400]
When I was upgrading NPM dependencies, at some point I deleted yarn.lock and after that I began to receive this error. I had @redux-devtools/cli@1.0.7 version. Tried upgrading to @redux-devtools/cli@2.0.0 but getting the same error.

The error I am getting in the browser is:

```
Ucaught TypeError: _socketclusterClient2.default.connect is not a function
    at start (devTools.js:225:42)
    at eval (devTools.js:319:21)
    at eval (redux.ts:137:1)
    at eval (redux.js:682:31)
    at createStore (redux.js:154:33)
    at configureStore (configureStore.ts:214:10)
    at eval (store.ts:35:36)
    at 59115 (app-src_state_app_h.js:36:1)
    at options.factory (runtime.js:675:31)
    at __webpack_require__ (runtime.js:36:33)
```

Redux DevTools is started from a Node.js script this way:

```js
import reduxDevTools from "@redux-devtools/cli";

const protocol = "https";
const host = process.env.DEV_TOOLS_HOST;
const port = process.env.DEV_TOOLS_PORT;

reduxDevTools({
  protocol,
  hostname: host,
  port,
  key: fs.readFileSync(process.env.TLS_KEY),
  cert: fs.readFileSync(process.env.TLS_CERT),
  // TODO: Attempts to upgrade to 2.x.x
  // key: path.join(__dirname, process.env.TLS_KEY),
  // cert: path.join(__dirname, process.env.TLS_CERT),
});
```

In the browser, I try to connect to the dev tools this way:

```js
import devToolsEnhancer from "remote-redux-devtools";

configureStore({
  devTools: false, // doesn't work inside GAS HTML

  // ...
  enhancers: [
    // ...
    devToolsEnhancer({
      name: "App",
      hostname: process.env.DEV_TOOLS_HOST,
      port: Number(process.env.DEV_TOOLS_PORT),
      secure: true,
    }),
  ]
})
```

Ready to quickly provide any additional information if needed.

**Comment by Methuselah96** [comment]
FYI, `redux-devtools-remote` was moved to this repository and is now named `@redux-devtools/remote`. Just added a notice to the old repository.
