### ISSUE TITLE
Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by 11111000000** [reduxjs/redux-devtools#1474]
Application on Angular + NgRX. Everything is connected according to the instructions. At first everything works normally, but when going to a certain screen, the devtools window becomes gray-blue, and we see an error in the devtools debugger console: 

```
Main._createAppUI: 18.43603515625 ms
main.js:1 Main._showAppUI: 182.698974609375 ms
main.js:1 Main._initializeTarget: 9.6337890625 ms
main.js:1 Main._lateInitialization: 2.664794921875 ms
4window.bundle.js:2 TypeError: Cannot read properties of undefined (reading 'type')
    at __.render (window.bundle.js:909:167382)
    at Ps (window.bundle.js:2:819887)
    at As (window.bundle.js:2:819685)
    at _l (window.bundle.js:2:863020)
    at wu (window.bundle.js:2:851223)
    at yu (window.bundle.js:2:851151)
    at vu (window.bundle.js:2:851014)
    at au (window.bundle.js:2:847821)
    at iu (window.bundle.js:2:846376)
    at S (window.bundle.js:2:898860)
ds @ window.bundle.js:2
window.bundle.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'type')
    at __.render (window.bundle.js:909:167382)
    at Ps (window.bundle.js:2:819887)
    at As (window.bundle.js:2:819685)
    at _l (window.bundle.js:2:863020)
    at wu (window.bundle.js:2:851223)
    at yu (window.bundle.js:2:851151)
    at vu (window.bundle.js:2:851014)
    at au (window.bundle.js:2:847821)
    at iu (window.bundle.js:2:846376)
    at S (window.bundle.js:2:898860)
DevTools failed to load source map: Не удалось загрузить контент для devtools://devtools/bundled/devtools-frontend/front_end/third_party/codemirror.next/codemirror.next.js.map: Неизвестная ошибка.
DevTools failed to load source map: Не удалось загрузить контент для devtools://devtools/bundled/devtools-frontend/front_end/third_party/codemirror.next/chunk/codemirror.js.map: Неизвестная ошибка.
```

**Comment by markerikson** [comment]
Dupe of #1198
