### ISSUE TITLE
Definition for rule 'jsx-quotes' was not found thrown after cloning and running npm install

### ISSUE THREAD

**Issue by jordan112** [reduxjs/redux-devtools#256]
1.  Cloned into a new directory

`git clone https://github.com/gaearon/redux-devtools.git redux-devtools1`
1.  Install dependencies

`npm install`
1.  Received the following error right away

```
/Users/shanejordan/Documents/repos/redux-devtools1/node_modules/eslint/lib/eslint.js:650
                    throw new Error("Definition for rule '" + key + "' was not found.");
                    ^

Error: Definition for rule 'jsx-quotes' was not found.
    at /Users/shanejordan/Documents/repos/redux-devtools1/node_modules/eslint/lib/eslint.js:650:27
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (/Users/shanejordan/Documents/repos/redux-devtools1/node_modules/eslint/lib/eslint.js:623:16)
    at processText (/Users/shanejordan/Documents/repos/redux-devtools1/node_modules/eslint/lib/cli-engine.js:201:27)
    at processFile (/Users/shanejordan/Documents/repos/redux-devtools1/node_modules/eslint/lib/cli-engine.js:226:12)
    at /Users/shanejordan/Documents/repos/redux-devtools1/node_modules/eslint/lib/cli-engine.js:322:26
    at /Users/shanejordan/Documents/repos/redux-devtools1/node_modules/eslint/lib/util/traverse.js:61:17
    at Array.forEach (native)
    at traverse (/Users/shanejordan/Documents/repos/redux-devtools1/node_modules/eslint/lib/util/traverse.js:41:54)
    at walk (/Users/shanejordan/Documents/repos/redux-devtools1/node_modules/eslint/lib/util/traverse.js:83:9)
```

**Comment by jordan112** [comment]
I am able to cd into examples\todomvc and run *npm install* successfully.  I can run the example app from there.

**Comment by gaearon** [comment]
Would you like to help fix it? Apparently it has to do with some ESLint misconfiguration.
